package com.ibm.apicine.enums;

public enum TipoEmpleado {
	SUPERVISOR_SALAS, SUPERVISOR_LIMPIEZA, SUPERVISOR_ALMACEN, SUPERVISOR_DULCERIA,SUPERVISOR_PROYECCION,
	GERENTE, SUBGERENTE, EMPLEADO_SALAS,EMPLEADO_LIMPIEZA, EMPLEADO_ALMACEN, EMPLEADO_DULCERIA, EMPLEADO_PROYECCION
}
